# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'iosDemo01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosDemo01
  pod 'Cosmos'
  pod 'AlamofireObjectMapper', '~> 5.2'

  target 'iosDemo01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
